// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veocymzbcxqaslvrbtww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlb2N5bXpiY3hxYXNsdnJidHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTY2NDYsImV4cCI6MjA2NTYzMjY0Nn0.4LrD2MG8Z6rX2BrlTPkmEj3cdNZbjvtHwxWF-GDESf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);